services:
  strapi:
    build:
      context: .
    container_name: strapi
    restart: unless-stopped
    image: keta-academy-cms:1.0.0
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - "127.0.0.1:1337:1337"
    volumes:
      - ./public/uploads:/opt/app/public/uploads
      - ./.tmp:/opt/app/.tmp
      - ./database:/opt/app/database
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1337/_health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: strapi-network
