services:
  strapi:
    build: .
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
    ports:
      - "127.0.0.1:1337:1337"
    volumes:
      - ./public/uploads:/opt/app/public/uploads

networks:
  default:
    name: strapi-network
